import type { HomeResponse } from '@/types/type.home';

export const MOCK_HOME: HomeResponse = {
  mainBannerList: [
    { bannerGuid: 'mb-1', title: '개발자 팀 매칭 플랫폼, DevHub' },
    { bannerGuid: 'mb-2', title: '나에게 맞는 프로젝트를 찾아보세요' },
    { bannerGuid: 'mb-3', title: '함께 성장하는 개발자 커뮤니티' },
  ],

  projectList: [
    {
      projectGuid: 'mock-p1',
      title: '[React/Spring] 개발자 포트폴리오 공유 플랫폼 팀원 모집합니다',
      recruitStatusCd: '3201',
      recruitmentTypeCd: '3001',
      progressRegionCd: '서울',
      recruitmentEndDate: '2026-06-20',
      positionList: ['백엔드 개발자', '프론트엔드 개발자'],
      skillList: ['React', 'Spring Boot', 'TypeScript'],
      username: '김개발',
      registeredDate: '2026.05.01',
      viewCount: 312,
    },
    {
      projectGuid: 'mock-p2',
      title: '[Flutter] 헬스케어 앱 MVP 개발 프로젝트 팀원 구합니다',
      recruitStatusCd: '3201',
      recruitmentTypeCd: '3002',
      progressRegionCd: '부산',
      recruitmentEndDate: '2026-05-31',
      positionList: ['앱 개발자', 'UI/UX 디자이너'],
      skillList: ['Flutter', 'Dart', 'Firebase'],
      username: '박플러터',
      registeredDate: '2026.05.02',
      viewCount: 189,
    },
    {
      projectGuid: 'mock-p3',
      title: '[AI/ML] 재난 안전 데이터 분석 공모전 팀원 모집 (대학생 환영)',
      recruitStatusCd: '3201',
      recruitmentTypeCd: '3001',
      progressRegionCd: '온라인',
      recruitmentEndDate: '2026-07-10',
      positionList: ['백엔드 개발자', '데이터 사이언티스트'],
      skillList: ['Python', 'TensorFlow', 'FastAPI'],
      username: '이데이터',
      registeredDate: '2026.05.03',
      viewCount: 427,
    },
    {
      projectGuid: 'mock-p4',
      title: '[Next.js/NestJS] 소셜 커머스 플랫폼 스타트업 창업 멤버 모집',
      recruitStatusCd: '3201',
      recruitmentTypeCd: '3001',
      progressRegionCd: '서울',
      recruitmentEndDate: '2026-06-05',
      positionList: ['풀스택 개발자', 'PM/기획자'],
      skillList: ['Next.js', 'NestJS', 'PostgreSQL'],
      username: '최창업',
      registeredDate: '2026.05.03',
      viewCount: 561,
    },
    {
      projectGuid: 'mock-p5',
      title: '[iOS/Android] 독서 기록 공유 소셜 앱 개발 팀원 모집합니다',
      recruitStatusCd: '3201',
      recruitmentTypeCd: '3002',
      progressRegionCd: '온라인',
      recruitmentEndDate: '2026-06-15',
      positionList: ['앱 개발자', '백엔드 개발자'],
      skillList: ['Swift', 'Kotlin', 'Node.js'],
      username: '정모바일',
      registeredDate: '2026.05.04',
      viewCount: 274,
    },
    {
      projectGuid: 'mock-p6',
      title: '[Vue.js/Django] 운동 루틴 커뮤니티 서비스 사이드 프로젝트',
      recruitStatusCd: '3201',
      recruitmentTypeCd: '3001',
      progressRegionCd: '경기',
      recruitmentEndDate: '2026-07-01',
      positionList: ['프론트엔드 개발자', '백엔드 개발자', 'UI/UX 디자이너'],
      skillList: ['Vue.js', 'Django', 'MySQL'],
      username: '강사이드',
      registeredDate: '2026.05.04',
      viewCount: 198,
    },
    {
      projectGuid: 'mock-p7',
      title: '[Spring/React] 취업 준비생을 위한 스터디 매칭 플랫폼 MVP',
      recruitStatusCd: '3201',
      recruitmentTypeCd: '3001',
      progressRegionCd: '서울',
      recruitmentEndDate: '2026-06-25',
      positionList: ['백엔드 개발자', '프론트엔드 개발자', 'UI/UX 디자이너'],
      skillList: ['Spring', 'React', 'Docker'],
      username: '윤스터디',
      registeredDate: '2026.05.05',
      viewCount: 389,
    },
    {
      projectGuid: 'mock-p8',
      title: '[Unity] 인디 게임 개발 팀 구성 중입니다 - 경력 무관',
      recruitStatusCd: '3201',
      recruitmentTypeCd: '3002',
      progressRegionCd: '온라인',
      recruitmentEndDate: '2026-06-10',
      positionList: ['게임 개발자', 'UI/UX 디자이너'],
      skillList: ['Unity', 'C#', 'Blender'],
      username: '임게임',
      registeredDate: '2026.05.05',
      viewCount: 512,
    },
    {
      projectGuid: 'mock-p9',
      title: '[AWS/Terraform] 클라우드 인프라 자동화 오픈소스 컨트리뷰터 모집',
      recruitStatusCd: '3201',
      recruitmentTypeCd: '3001',
      progressRegionCd: '온라인',
      recruitmentEndDate: '2026-07-31',
      positionList: ['DevOps 엔지니어', '백엔드 개발자'],
      skillList: ['AWS', 'Terraform', 'Kubernetes'],
      username: '조클라우드',
      registeredDate: '2026.05.06',
      viewCount: 345,
    },
    {
      projectGuid: 'mock-p10',
      title: '[React Native] 중고 거래 앱 리뉴얼 프로젝트 팀원 모집',
      recruitStatusCd: '3201',
      recruitmentTypeCd: '3001',
      progressRegionCd: '부산',
      recruitmentEndDate: '2026-06-18',
      positionList: ['앱 개발자', '프론트엔드 개발자'],
      skillList: ['React Native', 'TypeScript', 'Redux'],
      username: '한리액트',
      registeredDate: '2026.05.06',
      viewCount: 221,
    },
    {
      projectGuid: 'mock-p11',
      title: '[Figma/Webflow] 스타트업 브랜딩 및 웹사이트 디자인 협업',
      recruitStatusCd: '3201',
      recruitmentTypeCd: '3002',
      progressRegionCd: '온라인',
      recruitmentEndDate: '2026-05-28',
      positionList: ['UI/UX 디자이너', '프론트엔드 개발자'],
      skillList: ['Figma', 'Webflow', 'CSS'],
      username: '신디자인',
      registeredDate: '2026.05.07',
      viewCount: 163,
    },
    {
      projectGuid: 'mock-p12',
      title: '[FastAPI/React] 법률 정보 검색 AI 서비스 개발 파트너 구합니다',
      recruitStatusCd: '3201',
      recruitmentTypeCd: '3001',
      progressRegionCd: '서울',
      recruitmentEndDate: '2026-07-15',
      positionList: ['백엔드 개발자', '풀스택 개발자', 'PM/기획자'],
      skillList: ['FastAPI', 'React', 'LangChain'],
      username: '오AI',
      registeredDate: '2026.05.07',
      viewCount: 487,
    },
  ],

  subBannerList: [
    { bannerGuid: 'sb-1', title: '스킬 트렌드 분석 바로가기' },
    { bannerGuid: 'sb-2', title: '나의 관심 포지션 설정하기' },
    { bannerGuid: 'sb-3', title: '이번 달 인기 프로젝트 보기' },
    { bannerGuid: 'sb-4', title: '개발 스터디 모집 공고' },
    { bannerGuid: 'sb-5', title: '오픈소스 기여 프로젝트 찾기' },
  ],

  popularBoardList: [
    {
      boardGuid: 'mock-b1',
      categoryCd: '4001',
      title: 'Next.js 14 App Router 실무 적용기 — 이렇게 쓰니 훨씬 편하더라',
      likeCount: 243,
      viewCount: 1847,
      commentCount: 32,
      username: '이풀스',
      registeredDate: '2026.05.08',
    },
    {
      boardGuid: 'mock-b2',
      categoryCd: '4002',
      title: 'Spring Boot 3.x에서 JPA N+1 문제 해결 방법 정리해봤습니다',
      likeCount: 187,
      viewCount: 2341,
      commentCount: 47,
      username: '박스프링',
      registeredDate: '2026.05.07',
    },
    {
      boardGuid: 'mock-b3',
      categoryCd: '4001',
      title: '첫 사이드 프로젝트 배포 후기 — 도메인부터 HTTPS 까지 삽질 기록',
      likeCount: 312,
      viewCount: 3102,
      commentCount: 58,
      username: '김사이드',
      registeredDate: '2026.05.06',
    },
    {
      boardGuid: 'mock-b4',
      categoryCd: '4002',
      title: 'React Query v5 마이그레이션 하면서 달라진 점 총정리',
      likeCount: 198,
      viewCount: 2754,
      commentCount: 41,
      username: '최리액트',
      registeredDate: '2026.05.05',
    },
  ],
};
