export interface CommonCodeItem {
  code: string;
  parentCode?: string;
  name: string;
  depth?: number;
}

export type CommonCodeMap = Record<string, CommonCodeItem[]>;

export const COMMON_CODE = {
  SKILL_CODE: "SKILL_CODE",
  POSITION_CODE: "POSITION_CODE",
  POSITION_LEVEL_CODE: "POSITION_LEVEL_CODE",
  PROJECT_RECRUIT_TYPE: "PROJECT_RECRUIT_TYPE",
  PROJECT_PROGRESS_TYPE: "PROJECT_PROGRESS_TYPE",
  PROJECT_RECRUIT_STATUS: "PROJECT_RECRUIT_STATUS",
  PROJECT_APPROVAL_STATUS: "PROJECT_APPROVAL_STATUS",
  POST_CATEGORY: "POST_CATEGORY",
  REPORT_TYPE: "REPORT_TYPE",
  NOTIFICATION_TYPE: "NOTIFICATION_TYPE",
  REGION_CODE: "REGION_CODE",
} as const;

export type CommonCode = typeof COMMON_CODE[keyof typeof COMMON_CODE];

export const PROJECT_RECRUIT_TYPE = {
  GENERAL : {CODE:'3001', NAME:'일반 모집'},
  ADDITIONAL : {CODE:'3002', NAME:'추가 모집'},
} as const;

export const PROJECT_PROGRESS_TYPE = {
  RECRUITING: { CODE: '3201', NAME: '모집중' },
  COMPLETED: { CODE: '3202', NAME: '모집완료' },
  WAITING: { CODE: '3203', NAME: '모집대기' },
} as const;
  
export const ERROR_CODE = {
  INVALID_INPUT_VALUE : 'ERR.DVH.0001', // 400
  NOT_FOUND_API_KEY : 'ERR.DVH.0005', //400

  // //FORBIDDEN
  // HANDLE_ACCESS_DENIED : 'ERR.DVH.0004', // 403
  // NOT_ALLOW_SERVICE: 'ERR.DVH.2004', //403

  // METHOD_NOT_ALLOWED : 'ERR.DVH.0002' , // 405

  // API_NOT_FOUND : 'ERR.DVH.0011', //404 DVH에 API가 등록되지 않았습니다.

  // INVALID_QUERY_STRING : 'ERR.DVH.0003', // 500
  // DB_CONNECTION_ERROR : 'ERR.DVH.1000', //500
  // DB_ACCESS_ERROR : 'ERR.DVH.1001', //500
  // UNKNOWN_HOST : 'ERR.DVH.2002', //500
  // PROXY_SERVICE_NOT_CONNECT : 'ERR.DVH.2000', //500
  // PROXY_SERVICE_READ_TIMEOUT : 'ERR.DVH.2001', //500
  
  // // UNAUTHORIZED
  // INVALID_API_KEY : 'ERR.DVH.0006', //401
  // EXPIRE_API_KEY : 'ERR.DVH.0007', //401
  // NOT_EXIST_ACCESS_TOKEN : 'ERR.DVH.3002', //401 
  INVALID_ACCESS_TOKEN : 'ERR.DVH.3003', //401
  SIGNATURE_ERROR_ACCESS_TOKEN : 'ERR.DVH.3004', //401
  // MALFORMED_JWT_ERROR_ACCESS_TOKEN : 'ERR.DVH.3005', //401
  EXPIRE_ACCESS_TOKEN : 'ERR.DVH.3006', //401
  // UNSUPPORT_JWT_TOKEN : 'ERR.DVH.3007', //401
  // INVALID_TOKEN : 'ERR.DVH.3008', //401
  DUP_LOGIN : 'ERR.DVH.3010', //401
  
} as const;